name = "ash/ak-128"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'ash/ak-128'"

[repository]
user = "ash"
project = "ak-128"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"
